### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by zacker330** [elastic/elasticsearch-analysis-smartcn#39]
# When I:
/usr/share/elasticsearch/bin/plugin --url file:///home/vagrant/elasticsearch-analysis-smartcn-2.4.4.zip -i analysis-smartcn

# I got:
Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by dadoonet** [comment]
You did not download the plugin from Elastic download platform, or maven central.
Or You did not compile it by yourself.
But you downloaded source file from github.
Download the right zip file.
