### ISSUE TITLE
Issues with special characters and punctuation

### ISSUE THREAD

**Issue by redserpent7** [elastic/elasticsearch-analysis-smartcn#43]
Hi,

It seems the plugin has issue with punctuation marks. I have a document written in chinese with a couple of ',' to separate sentences. My issue is that whenever my search phrase includes a punctuation mark or a special character for ex: {'.', '_', '-', ';'} etc this document gets returned as a hit even though it does not contain any of these characters. Highlighting matches shows that ES detects the colons as the special character in the phrase.

This is how I define my chinese analyzer:

```
"zh_analyzer": {
                    "type": "custom",
                    "filter": [ "smartcn_word", "icu_normalizer", "icu_folding" ],
                    "tokenizer": "smartcn_sentence"
                },
```

And this is my search analyzer:

```
 "def_analyzer_search": {
                    "type": "custom",
                    "filter": [ "icu_normalizer", "icu_folding" ],
                    "tokenizer": "icu_tokenizer"
                },
```

**Comment by dadoonet** [comment]
Well. We only expose within this plugin features provided by Lucene Smart Chinese analysis module.

So if the result is different then what you expect, I'd suggest opening an issue on Lucene side?
