### ISSUE TITLE
[doc] provide more examples for smartcn analysis

### ISSUE THREAD

**Issue by twn39** [elastic/elasticsearch-analysis-smartcn#44]
Hi, I'm from china, and recently learning the elasticsearch, but I found it's hard to configure the smartcn analysis.I google this but find little documents. Could you help me or give me some documents, thank you very much.

**Comment by dadoonet** [comment]
I agree we should add more doc. in the meantime, you can read this https://github.com/elastic/elasticsearch-analysis-kuromoji

**Comment by twn39** [comment]
thanks

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13152
